### ISSUE TITLE
Support entity inheritance

### ISSUE THREAD

**Issue by thomasbaldauf** [sai-pullabhotla/catatumbo#105]
Right now, inheritance seems not to be supported properly, so one has to pull down properties of  superclasses (id being the most prominent) to also be present in concrete subclasses, redundantly. In Objectify inheritance of properties and annotations works out of the box, so people trying to migrate will encounter this issue. 

Example of a class hierarchy for entities that should be supported:

```
public abstract class CrudModel implements Serializable, Comparable<CrudModel> {
	
	@Identifier
	private Long id;	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
```

```
public abstract class PasswordCrudModel extends CrudModel {
	
	private String password;
	
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}

```

```
@Entity
public class MyEntity extends PasswordCrudModel {
	
	private Date created;	
	private String name;
	@Property(indexed = false)
	private String website;

```

In this example, MyEntity inherits the properties id and password from its respective superclasses, but Catatumbo ignores them. It would be a great improvement to also inspect properties of superclasses.

**Comment by sai-pullabhotla** [comment]
@thomasbaldauf - Inheritance is supported in Catatumbo through the use of MappedSuperClass annotation. All super classes of an Entity must have this annotation. In your specific example, you need to mark both CrudModel and PasswordCrudModel with @MappedSuperClass. Catatumbo then includes the fields from the super classes during persistence operations. 

JavaDoc - http://catatumbo.io/releases/catatumbo-1.2.0-javadoc/com/jmethods/catatumbo/MappedSuperClass.html 

A quick video tutorial on inheritance is available at - http://catatumbo.io/video-tutorials.html.

**Comment by thomasbaldauf** [comment]
Cool, that's working for me, thank you!
