### ISSUE TITLE
Unit testing with LocalServiceTestHelper fails

### ISSUE THREAD

**Issue by kcbanner** [sai-pullabhotla/catatumbo#106]
Given the following setup code:

```
public class ContextResourceTest {

	private final LocalServiceTestHelper helper =
		new LocalServiceTestHelper(new LocalDatastoreServiceTestConfig());

	private EntityManager em;

	@Before
	public void setUp() {

		helper.setUp();

		EntityManagerFactory emf = EntityManagerFactory.getInstance();
		em = emf.createDefaultEntityManager();

	}

	@After
	public void tearDown() throws IOException {
		helper.tearDown();
	}

	@Test
	public void testGetNew() {

		String contextId = "0";
		ContextState contextState = ContextResource.getOrCreateContext(em, "0");
		assertEquals(contextId, contextState.getId());
		assertEquals(0, contextState.getGoalProgress());
		assertEquals(null, contextState.getBoardState());

	}
 
... SNIP ...

	public static ContextState getOrCreateContext(EntityManager em, String contextId) {

		Optional<ContextState> maybeContextState = Optional.ofNullable(
			em.load(ContextState.class, contextId)
		);

		ContextState contextState = maybeContextState.orElseGet(() -> {
			ContextState newState = new ContextState(contextId);
			newState = em.insert(newState);
			return newState;
		});

		return contextState;

	}

```

I get the following errors:

``` 
Tests in error:
  testGetNew(com.bigvikinggames.animoji.ContextResourceTest): com.google.cloud.datastore.DatastoreException: The project test does not exist or it does not contain an active Cloud Datastore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=test to add a Cloud Datastore database. Note that Cloud Datastore always has an associated App Engine app and this app must not be disabled.
```

If I move the EntityManager creation before the `helper.setUp()`, things work, but the data is actually persisted to my local datastore.

What is the correct way to use  catatumbo under JUnit?

**Comment by kcbanner** [comment]
The problem is alleviated with this code:

```
@Before
	public void setUp() {

		EntityManagerFactory emf = EntityManagerFactory.getInstance();
		em = emf.createDefaultEntityManager();

		helper.setUp();

	}

	@After
	public void tearDown() throws IOException {
		em.deleteAll(ContextState.class);
		helper.tearDown();
	}

```

Although this doesn't appear to be using the actual test in-memory datastore, as I have some other tests that would write to the data that is being verified in the test I paste, and the values from those tests persist into the next run.

**Comment by sai-pullabhotla** [comment]
@kcbanner - EntityManagerFactory has separate methods to create an EntityManager for - 

### EntityManagerFactory.createLocalEntityManager 
Allows working with the Datastore Emulator (Local Datastore). The recommended way for this to work is to manually start the DatastoreEmulator before trying to use it. You can use a command like the one below to start the Emulator: 

```
gcloud beta emulators datastore start --data-dir=/my/data/dir --host-port="localhost:9999" --consistency 1.0
```

### EntityManagerFactory.createEntityManager/createDefaultEntityManager
Allows working with the real Datastore on GCP. 

Depending on where you want to run your unit tests against, choose the appropriate option. You might want to take a look at - 

https://github.com/sai-pullabhotla/catatumbo/blob/master/src/test/java/com/jmethods/catatumbo/EntityManagerTest.java

This is how I run the tests for Catatumbo itself. I use environment variables to control if tests should run against the Datastore Emulator or the Google Cloud Datastore. For an example on this, take a look at - https://github.com/sai-pullabhotla/catatumbo/blob/master/src/test/java/com/jmethods/catatumbo/TestUtils.java

Also, note that you don't need to create a new EntityManager for each test case. Initialize the EM in beforeClass and use it for all tests, unless you have a reason for creating a separate EM for each test.

**Comment by kcbanner** [comment]
Thanks! I see how it works there. Everything works if I point it at my datastore running locally.

 I'm wondering if there is a way to have the `createLocalEntityManager` connect to the datastore configured by the `LocalServiceTestHelper`? This way the tests can run say a CI server when the server is built without having to have a datastore emulator running there as well.

**Comment by kcbanner** [comment]
I was able to achieve this automatic startup like this:

```
	private static EntityManager em;
	private static LocalDatastoreHelper localDatastoreHelper;

	@BeforeClass
	public static void init() throws IOException, InterruptedException {

		localDatastoreHelper = LocalDatastoreHelper.create();
		localDatastoreHelper.start();

		DatastoreOptions options = localDatastoreHelper.getOptions();
		String host = options.getHost();

		EntityManagerFactory emf = EntityManagerFactory.getInstance();
		em = emf.createLocalEntityManager(host);

	}

	@AfterClass
	public static void shutdown() throws InterruptedException, TimeoutException, IOException {
		localDatastoreHelper.stop(Duration.standardSeconds(5));
	}

	@Before
	public void setUp() throws IOException {
		localDatastoreHelper.reset();
	}

	@After
	public void tearDown() throws IOException {

	}
```

Thanks for the help!

**Comment by sai-pullabhotla** [comment]
Awesome, thanks for sharing that tip. I will go ahead and close this.
