### ISSUE TITLE
Support certain types from java.time package to be used for CreatedTimestamp and UpdatedTimestamp fields. 

### ISSUE THREAD

**Issue by machinshin** [sai-pullabhotla/catatumbo#126]
@CreatedTimestamp & @UpdatedTimestamp should support more classes, including jodaTime & the java.time package from java8

**Comment by sai-pullabhotla** [comment]
@machinshin - would you please list the types that need to be supported (from Java 8)? Thanks.

**Comment by sai-pullabhotla** [comment]
Support certain types that represent a timestamp with timezone to be used as valid types for @CreatedTimestamp and @UpdatedTimestamp annotated fields.

**Comment by sai-pullabhotla** [comment]
Allow OffsetDateTime and ZonedDateTime to be valid types, in addition to the currently supported - Date, Calendar, Long and long.

**Comment by sai-pullabhotla** [comment]
Done.
