### ISSUE TITLE
Add support for Strongly Typed Identifiers

### ISSUE THREAD

**Issue by bnordli** [sai-pullabhotla/catatumbo#145]
We are using strongly typed identifiers, i.e. a different wrapper class for Long (or String) around each type of identifier. But Catatumbo doesn't play along with this, as identifier fields are restricted to be of type long, Long or String.

It would simply our entity classes a lot if we also could use any types *mappable* to String or Long as identifier types, as this code
```java
@Entity
public class Foo {
  @Identifier
  private Long idAsLong;
  ...

  public FooId getFooId() {
    return new FooId(idAsLong);
  }

  public void setFoodId(FooId fooId) {
    this.idAsLong = fooId.getValue();
  }

  public Long getIdAsLong() {
    return idAsLong;
  }

  public void setIdAsLong(Long idAsLong) {
    this.idAsLong = idAsLong;
  }
  ...
```

could be replaced with this:
```java
@Entity
public class Foo {
  @Identifier
  private FooId fooId;
  ...

  public FooId getFooId() {
    return fooId;
  }

  public void setFoodId(FooId fooId) {
    this.fooId = fooId;
  }
  ...
```
(where a suitable CustomMapper between FooId and Long is provided)

**Comment by sai-pullabhotla** [comment]
@bnordli - I'm not sure if Custom Mappers alone are sufficient for what you are looking for. Mappers just map/convert value from model to/from Datastore. Since these are Identifiers, we need to be able to handle other things, such as ID generation, if autogenerated is set to true. On the other hand, what are some of the benefits you would get with Strongly Typed IDs?

**Comment by bnordli** [comment]
Yes, you are right wrt the Mappers, it doesn't make sense to use a Mapper to just convert to and from ids. (Even though it in principle can be used, by first converting the values to LongValue or StringValue.) So here is another strategy:

### long/Long/String to FooId
I cannot imagine a scenario where the ID types do *not* have a single valued Long/String constructor, which can be found reflectively and used for conversion in this direction.

### FooId to long/Long/String
All ID types would have a (hopefully exactly one) method for conversion back to the underlying type. (Ours is called `getValue`.) You could either reflect over all methods of the type and pick the one with the return type matching the constructor type, or add a parameter to the Identifier annotation identifying the name of this method.

Alternatively, there could be a separate IdMapper concept (parallel to CustomMapper) that can take care of this, but I don't think this will be necessary, considering the simplicity of the types involved.

---
As for your question, there are very many benefits of using strongly typed IDs:

1. More errors are caught during compile time. (It is impossible to pass in FooId where a BarId is expected.) By extension this information can also be used by your IDE.
1. IDs can be validated upon construction (for instance to disallow negative values, or enforcing a certain structure to a String identifier).
1. Self documented API (what is the meaning of this long-argument, compared to this other long-argument) and code (i.e. compare Map<String, String> vs Map<PersonId, AddressId>).

**Comment by sai-pullabhotla** [comment]
@bnordli - here is what I propose: 

- Allow the field marked with @Identifier to be of any type (`long`, `Long`, `String`, `UserId`, `EmployeeId`, etc.) 
- If the type is not `long`, `Long` or `String`, the declared type must have a new annotation (e.g. `@IdClass`)

Classes marked with `@IdClass` annotation must conform to the following specs: 

- Must have public no-arg constructor 
- May have other constructors (not for framework's purpose)
- Must have a public `getValue` method with a return type of `long`, `Long` or `String` and no parameters
- Must have a public `setValue` method with a `void` return type and exactly one parameter of type `long`, `Long` or `String`. 
- The parameter type of `setValue` must be same as the return type of `getValue`
- Should not have any other state, framework will ignore, if any. 
- May have any other methods (not for the framework's purpose, for example, `toString`, `equals`, `hashCode`, `compareTo`, etc. 
- An `IdClass` may extend from another class (concrete or abstract), or implement any interfaces. For example, `public class UserId extends GenericStringId` or `public abstract class EmployeeId extends GenericLongId implements Serializable`. The super classes don't need any special annotations for the purpose of the framework. 

The framework will then take care of the ID mapping and auto-generation of Ids without any additional work. 

## Example ID Class: 

```
@IdClass
public class UserId {
  //Must be of type long, Long or String 
  private long value;
  public UserId() {
  }
  //Optional, will never be called by the framework 
  public UserId(long value) {
    this.value = value; 
  }
  public long getValue() {
    return value;
  }
  public void setValue(long value) {
    this.value = value;
  }
}

```
## Example Entity 

```
@Entity 
public class User {
  @Identifier 
  private UserId id;
  private String name;
  public UserId getId() {
    return id;
  }
  public void setId(UserId id) {
    this.id = id;
  }
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
}
```

Let me know what you think. If this looks good, I will take a stab at it this week.

**Comment by bnordli** [comment]
Thanks for picking this up!

Overall, the plan looks good, but I think the requirements are a little too strict:

* *Allow the field marked with `@Identifier` to be of any type (`long`, `Long`, `String`, `UserId`, `EmployeeId`, etc.)*
Yes!

* *If the type is not `long`, `Long` or `String`, the declared type must have a new annotation (e.g. `@IdClass`)*
I am reluctant to requiring an annotation on these classes, because id classes are ubiquitous, spreading everywhere through all parts of code (especially the business layer). Following good architectural practices (Dependency Injection/Inversion of Control or simply Clean Code), business code should be framework agnostic, but if the id classes require an annotation, these classes will necessarily have to reference the catatumbo specific annotation. (See http://blog.cleancoder.com/uncle-bob/2016/01/04/ALittleArchitecture.html for a good discussion of these principles.)
Yes, you can say that entities also necessarily have references to catatumbo annotations, but the gist of those objects can be abstracted away in an interface. And yes, the id classes themselves can also be made interfaces, abstracting away the concrete types used by catatumbo, but I think that will be too much plumbing for such simple classes.
Summing up: I don't see the need for this requirement, and think it will hurt clients.

*Classes ~~marked with `@IdClass` annotation~~ **used in `@Identifier` fields** must conform to the following specs:*

* *Must have a public `setValue` method with a `void` return type and exactly one parameter of type `long`, `Long` or `String`. The parameter type of `setValue` must be same as the return type of `getValue`*
I take on these first, because I strongly believe id classes should be allowed to be immutable, and the setter requirement would disallow this. I think catatumbo rather should use the constructor:

* *Must have public no-arg constructor*
Please change this to "Must have a public one-arg constructor taking either `long`, `Long` or `String`, but not more than one of these constructors" (or simply "Must have exactly one one-arg constructor, taking either `long`, `Long` or `String`"), so that this will become the principal method of constructing an id class.

* *May have other constructors (not for framework's purpose)*
This sounds good.

* *Must have a public `getValue` method with a return type ~~of `long`, `Long` or `String`~~ **matching the one-arg constructor parameter** and no parameters*
Yes, and this is the principal method of getting the value out of the id class.

* *Should not have any other state, framework will ignore, if any.*
Sounds like a superfluous requirement to me, but doesn't hurt to state.

* *May have any other methods (not for the framework's purpose, for example, `toString`, `equals`, `hashCode`, `compareTo`, etc.*
Yes, this is O.K. to state.

* *An `IdClass` may extend from another class (concrete or abstract), or implement any interfaces. [...] The super classes don't need any special annotations for the purpose of the framework. The framework will then take care of the ID mapping and auto-generation of Ids without any additional work.*
Yes, we simple extend every class from `LongId` or `StringId`, which take care of the plumbing (`equals`, `hashCode` etc).

### Example ID Class:

```
public class UserId {
  // (Really an implementation detail.)
  private long value;
  // Required, parameter must be the long, Long or String
  public UserId(long value) {
    this.value = value; 
  }
  // Required, must return the same type as the constructor accepts
  public long getValue() {
    return value;
  }
  // Optional, will never be called by the framework
  public UserId() {
  }
  // Optional, will never be called by the framework
  public void setValue(long value) {
    this.value = value;
  }
}
```

..and the entity will look exactly as you proposed.

How does this sound to you?

**Comment by sai-pullabhotla** [comment]
@bnordli - 

I'm okay with the Immutable Identifiers, but debating on whether or not to enforce the `@IdClass` annotation on the Identifier classes. Up until now, the framework was forcing some kind of annotation on the classes that participate in persistence. Not having this new annotation would deviate from that rule. 

I've almost completed the implementation of this without enforcing the annotation and will be checking in the code soon in a few hours. 

I will wait for a couple of days before I release this to see if anyone else have any thoughts/preferences on the `IdClass` annotation. If not, I will cut a release without it. I will let you know once the code is checked in so you can run some tests.

**Comment by sai-pullabhotla** [comment]
@bnordli - when you get a chance, please give it a test drive and let me know.

**Comment by bnordli** [comment]
Excellent! This works like a charm on our code. :) Thanks!

You say "Up until now, the framework was forcing some kind of annotation on the classes that participate in persistence.", which is only partly true: When using mappers, there are no annotation requirements on the field types themselves. (And the non-annotated standard classes `BigDecimal`, `Calendar` and `Date` are supported out of the box with the automatically registered mappers.) So I don't believe this is a deviation from the current practices.

Thanks again!

**Comment by sai-pullabhotla** [comment]
@bnordli  - version 2.1.0 is now available with this enhancement.

**Comment by bnordli** [comment]
Thanks, we have already started using it!
