### ISSUE TITLE
Support Collection of custom @Embeddable class 

### ISSUE THREAD

**Issue by nchiring** [sai-pullabhotla/catatumbo#155]
@Embeddable
public class Address {
..
}

@Entity(kind = "people")
public class Person {
   List<Address> shippingAddresses= new ArrayList<>(); 
   ...
}

**Comment by sai-pullabhotla** [comment]
@nchiring - This is already supported. You can have `Emeddable`s in various collection types (List/Set/Map). Please refer to https://github.com/sai-pullabhotla/catatumbo/blob/master/src/test/java/com/jmethods/catatumbo/EmbeddedCollectionTest.java for an example.

**Comment by sai-pullabhotla** [comment]
@nchiring - hope you got this to work. Please reopen if you are still having issues.
