### ISSUE TITLE
Support dynamic properties in entities

### ISSUE THREAD

**Issue by bnordli** [sai-pullabhotla/catatumbo#156]
One of the selling points of NoSQL databases are their flexible entities. As far as I can see, this is not supported by Catacumbo -- all entities will have all of its properties set upon insert, including possibly `NullValue`s if the field has not been set. (One could specify different entity classes with different properties, having the same kind, but this doesn't feel right.)

Here are two suggestions for supporting different set of properties on the same kind. (Let me know if you want to split them up.)

## 1. Optional properties
Add an option to not write the property at all if it is null. For example using an annotation specifying that the property should not be created if the field is not set. (My suggestion is `@Optional`.)

Example class:
```
@Entity
public class Foo {
  @Identifier
  private Long fooId;

  @Embeddable
  public static class Embed {
    @Optional
    private String embeddedProperty;

    [... getters and setters]
  }

  @Embedded
  @Optional
  private Embed exploded;

  @Embedded
  @Imploded
  @Optional
  private Embed imploded;

  @Optional
  private String optionalProperty;

  [... getters and setters]
}
```

`entityManager.insert(new Foo())` will currently result in an entity with three properties: `embeddedProperty`, `imploded` and `optionalProperty` (all set to `NullValue`). I would like to have this code not insert any properties at all. (It seems like the unmarshaller handles missing properties well.)

Still with this change, all possible property names must be known at compile time, so my second suggestion is:

## 2. Dynamic properties
Add an option to create a dynamic set of properties. This can be implemented in several ways, here are two suggestions:
### a. Using `Map`s
Allow properties of type `Map<String, Object>` to have the `@Exploded` annotation. When this field is inserted, each entry maps to a separate property, where the key specifies the name, and the value (after applying mappers) specifies the value. When the entity is loaded, properties that are not accepted by any other field of the entity should be inserted into this map. (A problem here might be to decide which mapper to use, but see below.) And care must be taken if keys collide with other fields during an insert (ignore the value or throw run-time exception?).

It might be reasonable to accept a more specific value type in the map, and for instance put all `String` values in a `Map<String, String>` field, and all `Long` values in a `Map<String, Long>` field (if present). This will solve the problem of selecting mappers. 

### b. Generalize `Mapper`s
Currently, a custom `Mapper` can only map fields to properties 1-to-1. It might make sense to expand this functionality to support mapping one field to many properties, just like the `@Exploded` fields do now. For example like:
```
public interface ExplodingMapper {
  public void toDatastore(Object input, BaseEntity.Builder<?, ?> entityBuilder);

  // Perhaps wrap the input in a state object that remembers all properties that have been read
  // so far by other mappers.
  public Object toModel(BaseEntity<?> input);
}
```
Then 2a (and the `@Exploded` handling) can be implemented in terms of this general mapper, and clients are free to define classes that explode in any way they like. Again, behavior must be defined if property names collide.

This last suggestion might be too complex, but I would really like to see some way to have dynamic properties in Catatumbo, and this is the most general solution.

---
What do you think? Are any of these suggestions reasonable and possible to implement?

**Comment by sai-pullabhotla** [comment]
@bnordli  

# Optional Properties 

This makes sense, but one needs to understand that **there is no way to find out the entities that are missing a specific property**. What would be the pros/cons of storing null vs. not storing the property altogether? A couple of benefits I could see are - 

- Viewing the Entities in GCD console keeps it clean 
- Less storage/cost 

Are there any other benefits to it that you would like to point out? 

# Dynamic Properties 
I always wanted to have this from the very beginning and reserved an Enum with the name `Unmodeled` (not in the domain model). It is currently unused. However as I was adding features and started supporting Maps, I did not see a need for this any more. One could simply define the below: 

```
@Entity 
public class Item {
  @Identifier 
  private long id;
  private String description;
  @Decimal(10, 2) 
  private BigDecimal price;
  //Dynamic or user defined properties (not developer defined) 
  private Map<String, Object> customProperties 
  }
}

```

Now you can add all your custom properties to the Map (e.g. color, size for a Shirt item, capacity, memory, processor, color for a Phone item). 

The one difference between your request and this is - the Map is stored in a single field, not in exploded form. Do you see any difference in the way the Map is stored (Imploded/Exploded)? How does it affect your application? 

Also, since the the type of Value in the Map is Object, the values are mapped using CatchAllMapper, which supports the following types: 

- Long
- Double
- Boolean 
- String 
- DatastoreKey 
- GeoLocation 

Of course, you can have more than one map to handle specific value types, but I think the basic types listed above should suffice in most cases. 

Let me know your thoughts and we will go from there.

**Comment by bnordli** [comment]
**Optional properties**: Yes, you are right about the search restrictions, but I believe most searches for optional properties go towards entities that have a specific value, not all entities that are *missing* this value (and otherwise you need to actually store `null`). It is mostly a matter of keeping the data -- and perhaps especially indices -- clean.

I am not hugely worried about storage costs, but if you have a property that has (a small amount of) data in only 1% of entities (and `null` on the rest), and you decide to index it, the index will be 100x larger than actually needed. (And each entity (with a long id) uses at least 60 bytes of data in the index, in addition to the property and kind name.)

Summing up, I think this is a nice feature to have, but not a very important one.

**Dynamic properties**: Nice that you already have an annotation for this! (I see you mention in the code that it only makes sense to have one `Map` per entity with this annotation.)

Actually, we are already using `Map<String, String>` in one of our entities, and yes, we are getting problems because of the imploded form: When any of the key values contain `.`, we get the following error: `com.google.cloud.datastore.DatastoreException: property.name contains a path delimiter, and the entity contains one or more indexed entity value.` We have identified four solutions to this problem:

1. **Turn off indexing for the property**: This works, but makes the property very hard to work with.
2. **Escape all dots** (for instance `a.b` -> `a_b`): This kind of works, but needs all sorts of special casing both during inserts, loads and queries.
3. **Manually explode into subentities**: We started implementing this, but stopped when we figured out there was no way to handle the two keys `a` _and_ `a.b` in the same entity. (Also, catatumbo could not handle maps as values inside maps, but that is a smaller problem.)
4. **Explode the map into separate properties**: Experimenting in the Cloud Console, indexed properties _can_  have dots in their names, and there can be properties with names `a` and `a.b` in the same entity. And the entity looks better in the Console.

We are currently doing 1, but would very much like to go with 4, otherwise we have to fall back to 2. So this was a little more background for our request.

I think the CatchAllMapper is a good solution for retrieving dynamic entities -- more mapping possibilities could be added later if needed. (As discussed above, maybe supporting `Map`s could be an acceptable solution for some clients.)

**Comment by sai-pullabhotla** [comment]
Not knowing what exactly you are trying to accomplish, I would like to ask - why is it so important for you to use a `dot (.)` in the property name of an EmbeddedEntity? How is it related to/how does it help if Catatumbo supports Map of Maps? Perhaps a more realistic example would help understand your requirements so we do this right. 

On the optional properties, we can avoid persisting properties that have a null value. What about if the fields of the entity are primitives, example `int`. Do we need to handle this as well and not store the property if the value is zero or have the developer specify a default value (e.g. don't store the property of my int field is 100)? Perhaps it is best to support @Optional on non-primitives? Any thoughts here?

**Comment by bnordli** [comment]
We are receiving an external data stream with some associated metadata. Different streams have different metadata keys, but some of them are common across streams. As we don't have control over the keys, we don't want to mess too much with their names (some have `.`s and some have `_`s), but we do want to group streams by metadata, or look up what kind of metadata we are receiving.

If Catatumbo supported map of maps, we could explode the map into a entityValue like this:
```
{ "properties": {
    "FOO": { "entityValue": { "properties": { "BAR": { "stringValue": "value for foo.bar" } } } },
    "BAZ": { "stringValue": "value for baz" }
} }
```
and still be able to select `WHERE customProperties.FOO.BAR = "value for foo.bar"`. Yes, this works, and is the reason dots are not allowed as property names in indexed properties in the first place.

We currently have no metadata where one key is a prefix of the other (FOO and FOO.BAR), but as we don't have control over them, we want to make sure to handle this case, which looks impossible to represent correctly.

Yes, `@Optional` only makes sense on reference types, IMO.

**Comment by sai-pullabhotla** [comment]
I think we should be able to support map of maps (nested to any level) when using a raw map. I will give that a try and let you know. I will create another ticket for the Optional fields.

**Comment by sai-pullabhotla** [comment]
Here is something that seems to do the trick. Would you please try this and let me know. 

[catatumbo-156.txt](https://github.com/sai-pullabhotla/catatumbo/files/1113854/catatumbo-156.txt)

**Comment by bnordli** [comment]
Yes, this works nicely, thanks!

With a small hack, representing `{"FOO" -> "x", "FOO.BAR" -> "y"}` as `{"FOO" -> { "_" -> "x", "BAR" -> "y"}}` in the common prefix case, this is an acceptable work around for us at the moment. (Inserting and loading works correctly, while querying has to be aware of the possibility of a renamed key.)

I still believe an exploding map has merit, but I also realize that requires much more work than these other small changes, and will let you prioritize accordingly.

(Just nitpicking, in `CatchAllMapper.java`, the new code returns early from the method, while all the other cases assigns to a return variable which is returned at the end.)

**Comment by sai-pullabhotla** [comment]
@bnordli - for the Optional properties - I've played around with it and thinking that it might be better to add a new attribute `optional=true/false` to the `Property `annotation. This is to allow overriding of fields defined in `MappedSuperClass `and `Embeddable`, using the `PropertyOverride `annotation. For example, an `Embeddable `may have 10 fields, but you want to make 2 of them optional in one entity while make 6 of them optional in another entity. Any thoughts?

**Comment by bnordli** [comment]
That sounds fine with me! Solves the problem, but is also more flexible!

**Comment by sai-pullabhotla** [comment]
Optional properties are implements as part of #157
