### ISSUE TITLE
Setting of Entity kind

### ISSUE THREAD

**Issue by sinsir** [sai-pullabhotla/catatumbo#164]
Hi,

I have a Document meta data object that wraps any model object

I wish to store the document using Catatumbo, but I cannot determine the kind to be used in its @Entity annotation at compile time, from its model object.

As well as the @Entity(kind="myKind") annotation, it would be ideal if we could set the kind on calls to the entity manager

for example

entityManager.insert(document, "myKind")

thanks

Gareth

**Comment by sai-pullabhotla** [comment]
@sinsir - would you please provide examples of your model classes and the expected data in the Datastore so I can further evaluate this? Thanks.
