### ISSUE TITLE
Disallowed literal: key EntityManagerException

### ISSUE THREAD

**Issue by bugyboo** [sai-pullabhotla/catatumbo#17]
Hi,
Came across this exception when using this GQL query. I don't know if it's a bug or I am missing something.

Thank you!

*******\* CODE ***********
EntityQueryRequest query = 
    em.createEntityQueryRequest("SELECT \* FROM SomeUnit WHERE **key** HAS ANCESTOR key(organization,'somename')");  

QueryResponse<SomeUnit> units = em.executeEntityQueryRequest(SomeUnit.class, query);

*******\* Exception ***********
com.jmethods.catatumbo.EntityManagerException: Disallowed literal: key.
    at com.google.datastore.v1beta3.client.RemoteRpc.makeException(RemoteRpc.java:126)
    at com.google.datastore.v1beta3.client.RemoteRpc.makeException(RemoteRpc.java:169)
    at com.google.datastore.v1beta3.client.RemoteRpc.call(RemoteRpc.java:89)
    at com.google.datastore.v1beta3.client.Datastore.runQuery(Datastore.java:108)
    at com.google.cloud.datastore.spi.DefaultDatastoreRpc.runQuery(DefaultDatastoreRpc.java:155)
    at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:93)
    at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:89)
    at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
    at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
    at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:88)
    at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:73)
    at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
    at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:82)
    at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:73)
    at com.jmethods.catatumbo.impl.BaseDatastoreAccess.executeEntityQueryRequest(BaseDatastoreAccess.java:378)
    at com.test.DatastoreTransactionTest.testUpdate(DatastoreTransactionTest.java:101)

**Comment by bugyboo** [comment]
It seems allow literal should be true to be able to execute that query and we can't access this value through the framework..

****\* CODE *****
GqlQuery gquery2 = Query.gqlQueryBuilder("SELECT \* FROM SomeUnit WHERE **key** HAS ANCESTOR key(organization,'somename')")
                **.allowLiteral**(true).build();
QueryResults<Entity> results2 = datastore.run(gquery2);

**Comment by sai-pullabhotla** [comment]
@bugyboo - I will go ahead and add a method to the QueryRequest to allow/disallow literals. In the meantime though, you should be able to use positional/named bindings. Assuming you have the Key (`com.jmethods.catatumbo.DatastoreKey`) of the Ancestor you are trying to search on - something like the below code should work: 

``` java
    @Test
    public void testExecuteEntityQuery_Ancestor() {

        ParentEntity pe = new ParentEntity();
        pe.setField1("Test for Ancestor Query");
        pe = em.insert(pe);

        for (int i = 0; i < 5; i++) {
            ChildEntity ce = new ChildEntity();
            ce.setField1("My ancestor is " + pe.getId());
            ce.setParentKey(pe.getKey());
            em.insert(ce);
        }

        sleep(5000);
        // NOTE that here we are using a positional binding for the ancestor
        // key.
        final String query = "SELECT * FROM ChildEntity WHERE __key__ HAS ANCESTOR @1";
        EntityQueryRequest request = em.createEntityQueryRequest(query);
        // Bind the key of the Ancestor
        request.addPositionalBinding(pe.getKey());
        QueryResponse<ChildEntity> response = em.executeEntityQueryRequest(ChildEntity.class, request);
        List<ChildEntity> results = response.getResults();
        for (ChildEntity result : results) {
            System.out.println(result.getId() + "--->" + result.getField1());
        }
    }

```

**Comment by bugyboo** [comment]
Thank you!! 
I was looking for that exactly.. Positional binding did the job.

**Comment by sai-pullabhotla** [comment]
@bugyboo, 

Thats great. I've also added the ability to use literals in the query, just in case... see 

Enhance the `QueryRequest` classes to allow/disallow literals in the query #18

for more information. I will include this in the next release, in the meantime, you can checkout the latest code, if needed.

**Comment by workmanw** [comment]
I'm having this issue and all I have is the Kind and the ID. I don't actually have a key instance and it doesn't seem like I can build one. I also cannot lookup the entity because it's been deleted and I'm trying to query for orphaned records. So my question is basically:

How do I query with the Key literal because I only have the ID -or- how do I manually build a key instance with the Kind and ID?

**Comment by sai-pullabhotla** [comment]
Hi @workmanw - 

If you have the Kind and ID - you would use one of the `load` methods provided in the `EntityManager`. For example - 

`
em.load(MyEntity.class, 1000L);
`

The `Kind` is determined from the `Entity` annotation on the `MyEntity` and a Key is built internally and looked up. 

You may also use GQL for this using the [synthetic literal](https://cloud.google.com/datastore/docs/reference/gql_reference#synthetic_literals) (or function), `KEY`. 

However, in order for this to work, you first need to allow literals in your query. This can be done with `setAllowLiterals(true)` on one of the `QueryRequest` (e.g. `EntityQueryRequest` or `KeyQueryRequest`) implementations. Without this call, you would get the `Disallowed Literal exception` from the Datastore. 

Hope this helps. Let me know if you need further assistance.

**Comment by workmanw** [comment]
Hey @sai-pullabhotla Thanks so much for the quick response. The biggest problem with `em.load(MyEntity.class, 1000L)` is that that entity has been deleted from the database already. So we cannot load it. In this case, I'm trying to clean up orphaned records in a task.

I noticed that in the native Google SDK you can create a DataStore Key, then I think I could pass that into the DefaultDatastoreKey implementation in Catatumbo. Does that seem like something that would work to build a key instance for querying?

**Comment by sai-pullabhotla** [comment]
Yes, you can use it as a workaround. I will add an enhancement request to make it a little easier in a future version.

**Comment by workmanw** [comment]
For anyone else interested, he was my workaround:

```java
Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
KeyFactory keyFactory = datastore.newKeyFactory().setKind("Album");
DatastoreKey albumKey = new DefaultDatastoreKey(keyFactory.newKey(id));

EntityManagerFactory emf = EntityManagerFactory.getInstance();
EntityManager em = emf.createDefaultEntityManager();
EntityQueryRequest request = em.createEntityQueryRequest("SELECT * FROM Photo WHERE album=@1 ORDER BY createdOn DESC");
request.addPositionalBinding(albumKey);
QueryResponse<PhotoModel> response = em.executeEntityQueryRequest(PhotoModel.class, request);
List<PhotoModel> photos = response.getResults();
```

**Comment by sai-pullabhotla** [comment]
You may also use the KEY literal as below to avoid using the underlying Datastore API: 

```
EntityQueryRequest request = "SELECT * FROM Photo WHERE album=KEY(Album, " + id + ") ORDER BY createdOn DESC";
request.setAllowLiterals(true);
QueryResponse<PhotoModel> response = em.executeEntityQueryRequest(PhotoModel.class, request);
```
Final query should look like 

```
SELECT * FROM Photo WHERE album=KEY(Album, 1000) ORDER BY createdOn DESC
```

Note that you cannot use parameter bindings (e.g. `@1` or `@AlbumId`) within the KEY literal/function.

**Comment by j-gao** [comment]
**Note that you cannot use parameter bindings (e.g. @1 or @AlbumId) within the KEY literal/function.** ahh!
