### ISSUE TITLE
Exception when persisting List values with indexing turned off for Embedded Objects

### ISSUE THREAD

**Issue by davidjoh0** [sai-pullabhotla/catatumbo#183]
The fix for https://github.com/sai-pullabhotla/catatumbo/issues/101 (https://github.com/sai-pullabhotla/catatumbo/commit/69ece205766a626ea89da2cf265c4fbade4b84d1) made a change in the `Marshaler` class to prevent setExcludeFromIndexes being set on ListFields.

`
if (valueBuilder.getValueType() != ValueType.LIST) {
valueBuilder.setExcludeFromIndexes(!propertyMetadata.isIndexed());
}
`

However, I believe a similar a similar change is required in `EmbeddedObjectMapper` to prevent this 'Exclude from indexes cannot be set on a list value' for Embedded Objects.

Thanks,

David Johnson

**Comment by sai-pullabhotla** [comment]
Hi @davidjoh0 - Thanks for reporting. I will look into it this week.

**Comment by davidjoh0** [comment]
many thanks 👍
