### ISSUE TITLE
duplicate id 

### ISSUE THREAD

**Issue by MuBoori** [sai-pullabhotla/catatumbo#187]
I'm using catatumbo 2.3.0 
I suddenly discover that catatumbo assign two entities with that same id. which I though it should be unique. The id is auto assigned. 
```


    @Identifier
    public Long id;
```

**Comment by sai-pullabhotla** [comment]
When using Long/long type for IDs, the ID generation is handled by the Datastore, not Catatumbo framework. Is it possible that you have manually inserted/imported some records into Datastore without first allocating the IDs?

**Comment by MuBoori** [comment]
thanks, maybe it seems a bug from google. because im running the backed app
for while without no duplication
 suddenly today i duplicated id. i think i would generate my id myself
instead
