### ISSUE TITLE
Strongly Consistent Ancestor Queries Not Working

### ISSUE THREAD

**Issue by derek-gfs** [sai-pullabhotla/catatumbo#189]
Below is some sample code that demonstrates how strongly consistent ancestor queries are not working as I would expect them to when running through Catatumbo.

Because of the eventual consistency of Google Cloud Datastore, I understand that I need to use an ancestor query if I want to achieve strongly consistent results.

When I use the Google Cloud Datastore GQL API directly (code below) I receive strongly consistent results.  When I use GQL through Catatumbo, I do not receive strongly consistent results, even though I am specifying the ancestor key in the query.  The results are eventually consistent.  

I would expect the Catatumbo GQL query to be strongly consistent, based on what i see in Google's documentation on the topic, and how Google's own GQL query API performs: https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/#ancestor-query-example

```
for (int u = 0; u < 100; u++) {
		int ordersCreatedForThisUser = 0;
		final String userId = UUID.randomUUID().toString();
		UserEntity userEntity = new UserEntity();
		userEntity.setId(userId);
		userEntity = em.insert(userEntity);

		for (int i = 0; i < 100; i++) {

			final String cartId = UUID.randomUUID().toString();
			CartEntity cartEntity = new CartEntity();
			cartEntity.setUserParentKey(userEntity.getDatastoreKey());
			cartEntity.setId(cartId);
			cartEntity.setCustomerId("customer");
			cartEntity.setPoNumber("Google Cloud Datastore");
			cartEntity.setUserId(userId);
			cartEntity.setLastUpdatedTimestamp(ZonedDateTime.now());
			
			cartEntity = em.insert(cartEntity);	
			ordersCreatedForThisUser++;				
			
			
			/**
			*
			* Try Catatumbo Query API
			*
			*/
			EntityQueryRequest ancestorKeyRequest = em.createEntityQueryRequest(
					"SELECT * WHERE __key__ HAS ANCESTOR KEY(UserEntity," + userId + ")");					

			QueryResponse<CartEntity> ancestorKeyResponse = em.executeEntityQueryRequest(CartEntity.class,
					request);
			List<CartEntity> cartEntityAncestorKeyList = ancestorKeyResponse.getResults();
			if (cartEntityAncestorKeyList.size() != ordersCreatedForThisUser) {
				System.out.println("Unexpected number of results returned from ancestor query"+ cartEntityAncestorKeyList.size() + " - " + ordersCreatedForThisUser);
			}

			/**
			*
			* Try Google Cloud Datastore GQL Query API
			* 
			*/
			Query<?> gqlQuery = Query.newGqlQueryBuilder("SELECT * From CartEntity WHERE __key__ HAS ANCESTOR KEY(UserEntity,'" + userId + "')").setAllowLiteral(true).build();
			QueryResults<?> gqlQueryResults = datastore.run(gqlQuery);
			int resultCountGql=0;
			while (gqlQueryResults.hasNext()) {
				gqlQueryResults.next();
				resultCountGql++;
			}
			if (resultCountGql != ordersCreatedForThisUser) {
				System.out.println("Unexpected number of results returned from GCD GQL Java API query" + resultCountGql + " - " + ordersCreatedForThisUser);
			}		
		}
	}
}
```

**Comment by sai-pullabhotla** [comment]
There should not be any difference between running queries with Catatumbo or the underlying low level API. Catatumbo essentially runs the same GQL you provide. 

That said, I do see that the two queries are different in the posted code. The first query is a Kind-less query, where as the second one is on CartEntity kind. Not sure if that is the issue. Please try again by adding FROM CartEntity (From clause) to the GQL of the Catatumbo and let me know if that makes a difference.

**Comment by derek-gfs** [comment]
Thanks @sai-pullabhotla.  

I thought of what you are asking about after I posted my first post, and tried exactly what you are asking about.   I made the queries exactly the same between the Google API & Catatumbo.   It does not make a difference if the "Kind" is in the query or not.  Catatumbo's GQL ancestor queries are eventually consistent and Google's GQL queries are strongly consistent.  

In order to reproduce this, the above code needs to run for "awhile", since Google Cloud Datastore's eventual consistency is pretty fast most of the time.

**Comment by sai-pullabhotla** [comment]
@derek-gfs  - Catatumbo GQL query and Google's GQL are NOT two separate things. Catatumbo runs the same code when running a query. Take a look at the code https://github.com/sai-pullabhotla/catatumbo/blob/master/src/main/java/com/jmethods/catatumbo/impl/DefaultDatastoreReader.java. Line 342. 

You might be running into some other issue. You need to understand the limitations on write rates for entity groups. 

Also, what happens if you swap your code to run the low level API first and then Catatumbo?

**Comment by sai-pullabhotla** [comment]
Closing this due to non-reproducibility/lack of response.
