### ISSUE TITLE
List<DatastoreKey> Property

### ISSUE THREAD

**Issue by bugyboo** [sai-pullabhotla/catatumbo#19]
Hi again :)

Is it possible to have a property with a type of `List<DatastoreKey>`in Entity?
because right now I'm using `List<String>` to store bunch of encoded keys.

For example, I have Entity named (User) and this user is a member of some (Groups). So, instead of creating another entity and store these keys. I put them in one list and store it in the User Entity.

Thanks 👍

**Comment by sai-pullabhotla** [comment]
The current version only supports `List<String>` and `List<Long>` for Array properties. I see that the gcloud-java-datastore api supports Keys and other types such as Boolean, Date, etc. It should be easy to add this, just need to enhance the `com.jmethods.catatumbo.impl.ListConverter` to handle the other data types. I will let you know once this is added.

**Comment by sai-pullabhotla** [comment]
@bugyboo , 

Support for this has been added under the below issue - 

Enhance support for Array properties #20

This will be included in the next release. In the meantime, feel free to checkout the latest code.

**Comment by bugyboo** [comment]
Great work 👍
