### ISSUE TITLE
Issue while using upsert method

### ISSUE THREAD

**Issue by dintualex** [sai-pullabhotla/catatumbo#190]
I'm using 2.4.0 version. Below is the snippet of maven dependency.

```
<dependency>
     <groupId>com.jmethods</groupId>
     <artifactId>catatumbo</artifactId>
     <version>2.4.0</version>
</dependency>

```
When i use create or update method separately its working fine without any issues. But when i use upsert method, its throwing the below exception.

Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:355)
	at com.jmethods.catatumbo.impl.DefaultDatastoreWriter.upsert(DefaultDatastoreWriter.java:385)
	at com.jmethods.catatumbo.impl.DefaultEntityManager.upsert(DefaultEntityManager.java:200)

This is related to guava jar, but since insert and update method are working, i'm confused.

Code Snippet

		EntityManagerFactory emf = EntityManagerFactory.getInstance();
		EntityManager em = emf.createEntityManager("ProjectId", inputStream,"namespace");
		
                em.insert(entity); --> This is working as expected.
                em.update(entity); --> This is working as expected.
                em.upsert(entity); --> Not working, throwing the exception.

**Comment by sai-pullabhotla** [comment]
@dintualex - My guess is that you have other dependencies in the project that are pulling a different version of Guava that is not compatible. Can you validate? It might be easier if you create a brand new project with just Catatumbo dependency and see if Upsert works.

**Comment by dintualex** [comment]
Tested with the correct version. Its working fine. Thanks Sai
