### ISSUE TITLE
Support for conditional index

### ISSUE THREAD

**Issue by firstthumb** [sai-pullabhotla/catatumbo#201]
In my current usage, unused null indexes have too much storage. I would like to have conditional index like in Objectify

`
@Index({IfNotNull.class, IfNotZero.class}) Long serialNumber;
`

_Reference_ : [Objectify Partial Indexes](https://github.com/objectify/objectify/wiki/Queries#partial-indexes)

**Comment by sai-pullabhotla** [comment]
Have you looked into the optional attribute of the Property annotation? I believe that will give you what you are looking for, as long as the values are null.

**Comment by sai-pullabhotla** [comment]
Closing this due to no response.
