### ISSUE TITLE
@Ignore Annotation is not ignoring fields when inserting an entity..

### ISSUE THREAD

**Issue by bugyboo** [sai-pullabhotla/catatumbo#3]
using version 0.1.0 
When using @ignore fields kept saving in Datastore.

**Comment by sai-pullabhotla** [comment]
Confirmed that this is a bug. The `com.jmethods.catatumbo.Ignore` Annotation class is missing Runtime Retention and hence and the annotation is not preserved at runtime.

**Comment by sai-pullabhotla** [comment]
Fixed the issue and added test cases for Insert, Update and Load of fields with `@Ignore` annotation

**Comment by sai-pullabhotla** [comment]
@bugyboo - just wanted to thank you for reporting this. Also wanted to let you know that the new version 0.2.0 has a fix for this.

**Comment by bugyboo** [comment]
Thanks to you for making this amazing framework. 🌷
