### ISSUE TITLE
Custom converters

### ISSUE THREAD

**Issue by arthur-tse7** [sai-pullabhotla/catatumbo#47]
I've been starting to use this library, and I've been liking it a lot. I'm wondering if you currently support custom converters. For example, if I have an enum Color declared like this:

``` java
public enum Color {
    RED, YELLOW, GREEN;
}
```

Using EnumConverter, this is stored in the Datastore as a String in the form of RED, YELLOW, or GREEN. Is there a way I can write my own converter so that I can convert it to say an Integer or format it differently as a String ? An example would be like how Jackson allows you to create your own custom serializers and deserializers.

**Comment by sai-pullabhotla** [comment]
@arthur-tse7, 

Glad to hear that you are liking the Catatumbo framework. 

When I was implementing support for Enums, I debated if I should give the option like JPA, to map Enums by their ordinal position or name - 

https://docs.oracle.com/javaee/7/api/javax/persistence/Enumerated.html 

I then felt that using ordinal positions is error prone, especially in the case where a developer does not add a new Enum constant to the end of the list. That is why I went with the String based implementation. 

That said, providing an option to specify a Custom Converter (or Mapper) is a great idea and gives a lot of flexibility to the developers who need it. Currently, there is no support for this. I will explore this a little more and see what I can do. 

In the meantime, would you please let me know your specific requirement? Do you just need the ability to map enums by their ordinal position or do you really want a custom mapper?

**Comment by arthur-tse7** [comment]
It's not a big issue, mainly I wanted to convert from Color.RED to store as "red" within Google Datastore. As for the custom mapper, I think it would be great to have one or at least a way that I can implement my own custom mapper. I noticed that you support java.util.Date and java.util.Calendar. Say I have an Entity class with a LocalDate property. Then I could implement a custom mapper to convert that LocalDate into a Datastore date or convert it into a String.
Edit: @sai-pullabhotla, let me know if I can be of any help !

**Comment by sai-pullabhotla** [comment]
@arthur-tse7 - See Issue #72 that addresses custom converters. Feel free to clone the project and see if it addresses your requirement. Appreciate your feedback. I will be cutting a release in the next couple of days.
