### ISSUE TITLE
Ancestors and Support for Builder patterns

### ISSUE THREAD

**Issue by arthur-tse7** [sai-pullabhotla/catatumbo#48]
@sai-pullabhotla 
Sorry to continuously bother you, but I have a few more questions. 
If I had a Parent entity and a Child entity, I would like to be able to store a reference to the parent using its UID.

``` java
@Entity
public class Parent {
@Identifier
private long id;
}

@Entity
public class Child {
@Identifier
private long id;

private long parentId;
}
```

Parent would be an ancestor Child and Child a descendant of Parent. Is there anyway to generate an Entity with the ancestor path specified ?

Also, is there support for mapping using a specific constructor method ? I believe you use the empty args constructor and then setters, but I would like to have immutability on some fields.

Again, if I can help out with anything, feel free to let me know !

**Comment by sai-pullabhotla** [comment]
@arthur-tse7, 
No worries... I do like to get some feedback and appreciate whatever you can do to contribute. 

As far as dealing with ancestors, the framework has two annotations - `@Key` and `@ParentKey`. Take a look at the test entities that I used for testing at - 

https://github.com/sai-pullabhotla/catatumbo/tree/master/src/test/java/com/jmethods/catatumbo/entities

Check out the ParentEntity, ChildEntity and GrandchildEntity for an example. There are test cases using these entities in https://github.com/sai-pullabhotla/catatumbo/blob/master/src/test/java/com/jmethods/catatumbo/EntityManagerTest.java 

From the DatastoreKey, you can retrieve the ID, where needed by calling the id() or name() methods. 

On the 2nd question on immutable fields, I've never thought about it, but if you could open a separate ticket to track this and submit a proposal or share some ideas, that would be of great help.

**Comment by sai-pullabhotla** [comment]
@arthur-tse7, Thanks for opening the other issue for supporting immutable properties. Were you able to get the Ancestor keys working? Let me know, so I can close this issue.

**Comment by arthur-tse7** [comment]
@sai-pullabhotla I haven't gotten around to using it, but looking at your examples, it's perfect for what I need it for. You can close this !
