### ISSUE TITLE
Mapping Exception when mapping Float value <= 0

### ISSUE THREAD

**Issue by pierredeman** [sai-pullabhotla/catatumbo#82]
When using a **float** in an entity : 
>Caused by: com.jmethods.catatumbo.MappingException: Value 0.000000 is out of range for float type
	at com.jmethods.catatumbo.mappers.FloatMapper.toModel(FloatMapper.java:51)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalProperty(Unmarshaller.java:343)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalWithImplodedStrategy(Unmarshaller.java:306)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshalEmbeddedFields(Unmarshaller.java:236)
	at com.jmethods.catatumbo.impl.Unmarshaller.unmarshal(Unmarshaller.java:139)
>	... 31 common frames omitted

In **FloatMapper.java**, maybe using something like : 
```java
final DoubleValue value = (DoubleValue) input;
final Double d = value.get();
final float f = d.floatValue();
if (d != f) {
    throw new MappingException(String.format("Value %f is out of range for float type", d));
}
```

**Comment by sai-pullabhotla** [comment]
@pierredeman - 

This is very interesting! I never realized that `Float.MIN_VALUE` is **not** really the minimum value, but is: 

> A constant holding the smallest **positive nonzero value** of type float, 2-149. 

We need to fix the range (especially `MIN_VALUE`) to ensure the value retrieved from the Datastore is a valid value in the float's range. 

Perhaps the `MIN_VALUE` should be `-Float.MAX_VALUE`. 

I'm not sure if the proposed fix `d != f` would be the best solution as there are numbers that cannot be represented exactly when using Floating points. I've read posts that equality/inequality checks should not be used with floating point numbers. 

Any further feedback is welcome. I will try and fix the range and provide some additional unit tests to make sure it works as expected.

**Comment by sai-pullabhotla** [comment]
Related to - Validate data when mapping Datastore value to a model value for certain types #50. This when we added the range check.

**Comment by pierredeman** [comment]
You're right, a simple case is : 

``` java
final Double d = 3.2;
final float f = d.floatValue();
System.out.println(d == f);
```

After few researchs, I just made another commit to change to -Float.MAX_VALUE.

**Comment by sai-pullabhotla** [comment]
Fixed the range check. Added several test cases for the FloatMapper. Updated the test cases for the entity manager for Float/Double for negative values.
