### ISSUE TITLE
Enhance support for List/Set/Map to cover embedded entity types

### ISSUE THREAD

**Issue by pierredeman** [sai-pullabhotla/catatumbo#87]
Add ability to define fields like `List<MyObj>` where `MyObj` is an Embeddable entity like
```java
@Embeddable
public static class MyObj{
    private String name;
    private int level;

    //... GETTERS/SETTERS ...
}
```

**Comment by sai-pullabhotla** [comment]
Implemented a new Mapper to map Embedded objects to Embedded Entities and vice versa. While this mapper is created primarily for mapping Collection of Embeddables, it opened up the possibility to map non-collection Embeddables to Embedded Entities.  This means, it is not required to use @Embedded & @Imploded combination to store embedded objects as Embedded Entities.

**Comment by sai-pullabhotla** [comment]
@pierredeman - If you get a chance, please try out the latest commit and let me know. I will try to cut a release in a week or two.

**Comment by pierredeman** [comment]
I made some tests, all seems good for me.
Embeddable Objects in List and maps are saved.
Waiting for your future release... Thanks a lot.

**Comment by sai-pullabhotla** [comment]
That's great to hear. I hope to get a release out this weekend with the below feature also included: 

Support Secondary (or Helper Indexes) for case-insensitive querying #86

**Comment by sai-pullabhotla** [comment]
@pierredeman - the new version, 1.1.1, is now available on Maven Central.
